/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as SimulatorIdRouteImport } from './routes/simulator.$id'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorIdRoute = SimulatorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SimulatorRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/leads': typeof LeadsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/leads/$id': typeof LeadsIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/simulator/$id': typeof SimulatorIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/leads': typeof LeadsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/leads/$id': typeof LeadsIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/simulator/$id': typeof SimulatorIdRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/leads': typeof LeadsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/leads/$id': typeof LeadsIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/simulator/$id': typeof SimulatorIdRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/auth'
    | '/leads'
    | '/settings'
    | '/simulator'
    | '/admin/users'
    | '/leads/$id'
    | '/profile/$userId'
    | '/simulator/$id'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/auth'
    | '/leads'
    | '/settings'
    | '/simulator'
    | '/admin/users'
    | '/leads/$id'
    | '/profile/$userId'
    | '/simulator/$id'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/auth'
    | '/leads'
    | '/settings'
    | '/simulator'
    | '/admin/users'
    | '/leads/$id'
    | '/profile/$userId'
    | '/simulator/$id'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  AuthRoute: typeof AuthRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator/$id': {
      id: '/simulator/$id'
      path: '/$id'
      fullPath: '/simulator/$id'
      preLoaderRoute: typeof SimulatorIdRouteImport
      parentRoute: typeof SimulatorRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface SimulatorRouteChildren {
  SimulatorIdRoute: typeof SimulatorIdRoute
}

const SimulatorRouteChildren: SimulatorRouteChildren = {
  SimulatorIdRoute: SimulatorIdRoute,
}

const SimulatorRouteWithChildren = SimulatorRoute._addFileChildren(
  SimulatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  AuthRoute: AuthRoute,
  LeadsRoute: LeadsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
