/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as LeadsIdRoofRouteImport } from './routes/leads.$id.roof'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsIdRoofRoute = LeadsIdRoofRouteImport.update({
  id: '/roof',
  path: '/roof',
  getParentRoute: () => LeadsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/leads': typeof LeadsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/leads/$id': typeof LeadsIdRouteWithChildren
  '/leads/$id/roof': typeof LeadsIdRoofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/leads': typeof LeadsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/leads/$id': typeof LeadsIdRouteWithChildren
  '/leads/$id/roof': typeof LeadsIdRoofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/leads': typeof LeadsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/leads/$id': typeof LeadsIdRouteWithChildren
  '/leads/$id/roof': typeof LeadsIdRoofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/leads'
    | '/settings'
    | '/leads/$id'
    | '/leads/$id/roof'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atlas' | '/leads' | '/settings' | '/leads/$id' | '/leads/$id/roof'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/leads'
    | '/settings'
    | '/leads/$id'
    | '/leads/$id/roof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$id/roof': {
      id: '/leads/$id/roof'
      path: '/roof'
      fullPath: '/leads/$id/roof'
      preLoaderRoute: typeof LeadsIdRoofRouteImport
      parentRoute: typeof LeadsIdRoute
    }
  }
}

interface LeadsIdRouteChildren {
  LeadsIdRoofRoute: typeof LeadsIdRoofRoute
}

const LeadsIdRouteChildren: LeadsIdRouteChildren = {
  LeadsIdRoofRoute: LeadsIdRoofRoute,
}

const LeadsIdRouteWithChildren =
  LeadsIdRoute._addFileChildren(LeadsIdRouteChildren)

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRouteWithChildren
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRouteWithChildren,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  LeadsRoute: LeadsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
